volumes:
  postgres:

services:
  postgres:
    image: postgres:17.0-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
